### ISSUE TITLE
Paths on Mac OS X (steam)

### ISSUE THREAD

**Issue by ketch** [jcranmer/factorio-tools#2]
I got this working on a Mac with a steam install by setting:

```
FACTORIO_PATH = os.path.join(
    os.path.expanduser("~"), "Library", "Application Support", "Steam", "steamapps", "common",
    "Factorio", "factorio.app", "Contents")
```
```
MOD_PATH = os.path.join(os.path.expanduser("~"), "Library", "Application Support", "factorio", "mods")
```

Also, for the uninitiated it would be great to give a list of dependencies and to mention how to open the webpages (e.g., http://localhost:5000/ratio), along with a list of the pages that are created.

**Comment by jcranmer** [comment]
I just pushed a set of commits which should fix both of these issues.
