### ISSUE TITLE
Time for a recipe

### ISSUE THREAD

**Issue by xapple** [jcranmer/factorio-tools#6]
Hi !
Great little module you made. I was thinking of using this for a python script I wanted to make. It's perfect to extract all the required info for recipes and such.

It's missing some example usage code, but I'll post what I have here:

    $ git clone git@github.com:jcranmer/factorio-tools.git
    $ brew install lua
    $ pip install --user lupa
    $ python
    >>> import factorio
    >>> f = factorio.load_factorio()
    >>> r = f._data['recipe']
    >>> [(x, list(y.items())) for x,y in r['laser-turret']['ingredients'].items()]
    [(1, [(1, u'steel-plate'), (2, 20)]),
     (2, [(1, u'electronic-circuit'), (2, 20)]),
     (3, [(1, u'battery'), (2, 12)])]

One thing I'm unable to find, is the time required for a recipe. In the case of a laser turret it's 20, as you can see on the wiki: https://wiki.factorio.com/Laser_turret

Where can you find this information ?

**Comment by jcranmer** [comment]
The time on a recipe is listed as "energy_required"
